version: '3.8'

services:
  web:
    build: .
    container_name: php_app
    ports:
      - "2580:80"  # Перенаправление порта 8080 на 80
    volumes:
#      - .:/var/www/html  # Подключение локальных файлов к контейнеру
      - /var/spool/asterisk/outgoing/.:/var/www/html/finalfolder
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
#    depends_on:
#      - db
    networks:
      - app-network

#  db:
#    image: mysql:8.0
#    container_name: mysql_db
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: app_database
#      MYSQL_USER: app_user
#      MYSQL_PASSWORD: app_password
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
